### ISSUE TITLE
Will need to extend loadRewards

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK#11]
@alamboley In order for getCredits to work, you have to extend loadRewards so that it will sync from the server. getCredits is a synchronous call to retrieve the balance from local storage. The usual flow is
loadRewards -> getCredits (in callback)

**Comment by aaustin** [comment]
Sorry - it's counter to our normal paradigm of method(callback)

**Comment by alamboley** [comment]
@aaustin that's what I'm already doing ;) https://github.com/BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK/blob/master/ios/BranchIosExtension/BranchIosExtension/BranchHelpers.m#L112 https://github.com/BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK/blob/master/android/src/io/branch/nativeExtensions/branch/functions/GetCreditsFunction.java#L22

**Comment by aaustin** [comment]
Oh my bad - traced the code to the main file but stopped there. I added docs on our portal for all languages but didn't know we were supporting credits on ANE. https://dev.branch.io/recipes/quickstart_guide/adobe/ Awesome!

**Comment by alamboley** [comment]
Yeah, I need to update the README ;)
