### ISSUE TITLE
Received report that the Android intent is not stripped of link_click_id

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK#12]
In native Android, we pass in the intent data from the Activity and strip out the link_click_id. This is meant to prevent the intent from persisting and being re-processed when the app is backgrounded and reopened from the menu. Android doesn't seem to clear the intent data in this scenario...

Is this our problem or the partner's? @alamboley let me know if you have bandwidth to look into it.

**Comment by alamboley** [comment]
Hmm I'm not 100% sure, but things concerned by Intent are always down on the native side.

Could you be a bit more precise? I'm not sure to fully understand.

**Comment by aaustin** [comment]
Sorry for the delay! In the Android SDK, we call:
```java
branch.initSession(new Branch.BranchReferralInitListener(){
    @Override
    public void onInitFinished(JSONObject referringParams, BranchError error) {
}, this.getIntent().getData(), this);
```

Where we pass in this.getIntent().getData(). The internals of the Branch SDK then strip out the Branch data from the intent. This is important because Android doesn't clear the intent on minimize/reopen, which could cause us to consume an old intent if we didn't clear it.

Are we passing the intent on the Android side? Not sure if it's possible. We had a partner complain that after linking once, and receiving the intent, subsequent reopens of the app would consume the same intent.

**Comment by alamboley** [comment]
At the moment that's why I'm doing https://github.com/BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK/blob/b5e42c6699883b2031ce7084dea47e713fe9fabb/android/src/io/branch/nativeExtensions/branch/BranchActivity.java#L28
You think to merge it directly in the native SDK instead of the Android call, right?

**Comment by aaustin** [comment]
Oh no - I just wanted to make sure we handle the case which it looks like we do just fine. I'll work with them to figure out why it's not being registered.
