### ISSUE TITLE
Clearing session params?

### ISSUE THREAD

**Issue by alamboley** [BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK#13]
Quick question form @jfreeney: 
> sessionParams are persistent until you background the app and I want to be able to clear them once I use them. Basically if i use them and then they kill the app and relaunch it they come back. Is there a way to create that function call to clear session params?

I didn't find anything for achieving this. Did we missed something? @aaustin @shortstuffsushi

**Comment by shortstuffsushi** [comment]
No, we don't currently provide a method for this, and I'm not sure that it would make sense for us to. SessionParams are supposed to represent the init dictionary for that session, it wouldn't make sense if that was only true *sometimes*, and could be affected by developers. I think the best solution for this specific request would be for you to wrap that function with your own that will only return the values once per "session" if that's the behavior you're looking for.

**Comment by jfreeney** [comment]
Hmm I can not seem to reproduce the issue I was seeing where the session params were restored on a fresh launch. Thank you for the info and I will update if I can reproduce the issue.

**Comment by shortstuffsushi** [comment]
Oh, perhaps I'm not understanding the issue you're seeing. I thought you were saying that you want them to be removed after you've used them (via manually clearing them). Are you saying that you're seeing an issue where they aren't cleared between sessions? If that's the case, that's something we will need to fix.

**Comment by jfreeney** [comment]
That is correct - it was not clearing between sessions. It happened while I was debugging on device though so it may have been a fluke (during a crash/manual app close without going to background first). My solution was to create a manual clear session call so you for sure knew when I was done with the session data. This also would provide a good moment to send you a report of what happened with this link. Imagine Branch getting analytical feedback as to what developers are doing with the links and being able to track what links are actually useful or not. This functionality is not required though and right now I don't think we need any action until I can reproduce the issue.

**Comment by shortstuffsushi** [comment]
If you're seeing an issue with things not getting cleared between runs, please let us know -- that one is important for us to fix.

I don't think we'll offer an option to manually clear your session (short of actually logging out the user), as that would get us into a bunch of other potential "bad state" scenarios. We do actually have a request that pings back on "session close" to let us know when sessions have ended, so we are getting that info at least.

Re: what links are useful, we can basically judge that by how frequently links are opened, and how many of them lead to installs, etc. For you as a developer, additional info like whether the user signed up, and what via which platform, etc, may be useful, which is what we offer the UserCompletedAction functionality for (that and triggering credit rules). However, this level of behavior isn't something that we want to track for all apps -- these events aren't universal like "install," "open," and "close" that we handle automatically.

**Comment by jfreeney** [comment]
I will let you know if I can reproduce the issue. Thank you for taking the time to write this up. It helps me know why you are making the decisions you are making.

:)
