### ISSUE TITLE
Issue implementing application:continueUserActivity:restorationHandler: 

### ISSUE THREAD

**Issue by alamboley** [BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK#15]
Hey @jfreeney @shortstuffsushi @aaustin,

Following Josh discussion, I tried to implement https://dev.branch.io/recipes/branch_universal_links/ios/#integrate-code-snippet-with-appdelegate unfortunately my Objective-C knowledge is there limited.

I can't implement directly the Objective-C method due to the ANE architecture (long topic https://forums.adobe.com/thread/948727?start=0&tstart=0  examples https://github.com/freshplanet/ANE-Push-Notification/blob/master/ios/AirPushNotification/AirPushNotification.m#L92), I've to do some objc method swizzling for adding core AppDelegate method.

I tried to add the method but without luck https://github.com/BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK/blob/master/ios/BranchIosExtension/BranchIosExtension/BranchIosExtension.m#L220 I don't know how I should write this part `void (^)(NSArray *restorableObjects))restorationHandler`. You can see examples for the other methods: *applicationOpenURLSourceApplication*, *applicationDidFinishLaunchingWithOptions*.

Thanks.

**Comment by aaustin** [comment]
Hey @alamboley - thanks for all the details. This looks like it should work to me. Why do you say you did it without luck? What makes you think it doesn't work?

If you think it's breaking because of the restoration handler, can you just use `id` (the generic pointer) as type for it? We don't need it.

**Comment by alamboley** [comment]
Well, if you open the Xcode project, you won't be able to build it (due to this method) :(

**Comment by aaustin** [comment]
Here are you sir: https://github.com/BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK/commit/f8e9ea6b5d1eb66c2691bef7162e61de425836b9

@jfreeney Should be good to go?

**Comment by alamboley** [comment]
:+1:
