### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by jfreeney** [BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK#2]
add type,duration,alias and other parameters to the getShortUrl function

add credits functionality and dynamic reward rules

add branch referral code functionality

add Branch App management functionality

**Comment by jfreeney** [comment]
I also am not getting good data from InvokeEvent.INVOKE event arguments when I have the ANE added. This is breaking our other deeplink functionality.

and right now you have to define the branch key in the app xml - can we make it so you pass that in to the app so it is easier to toggle between live and testing?

**Comment by alamboley** [comment]
Could you describe me at which moment do you have issues with the Invoke Event? On Android only? When you launch the ANE or at any time?

Well, that's what I did for the first version, but I think it's deprecated. Is it right @aaustin ?
Also, @aaustin, is there any automatic choice, if there is a live & testing key?
I could just add a var on the ANE side to tell which one use ;)

**Comment by jfreeney** [comment]
The invoke event fires but does not seem to pass though arg data on iOS when the app is already open. I have not tested on first launch or on android.

**Comment by alamboley** [comment]
Do you use other ANEs? If you just use the Branch ANE, do you also have the issue?

**Comment by jfreeney** [comment]
If I just use the branch on its own it happens - I will try some more testing

**Comment by alamboley** [comment]
[applicationOpenURLSourceApplication](https://github.com/BranchMetrics/Branch-AIR-ANE-SDK/blob/master/ios/BranchIosExtension/BranchIosExtension/BranchIosExtension.m#L114) is probably causing the issue. However I never saw an other way to implement it. I will have a look.
We should create several issues on this Github it would be easier to manage & follow later.

**Comment by jfreeney** [comment]
sounds good. Can you spin them off in language you would understand?

**Comment by alamboley** [comment]
Certainly, done. I keep this one for the features to add (those on top), and will open new issue when an other problem is identified or an other feature request.

**Comment by aaustin** [comment]
Let me know if you need anything from me @alamboley

**Comment by aaustin** [comment]
Can you make sure to pull in the latest version of iOS since you're doing it for Android for the task to leverage Branch App tracking?

**Comment by alamboley** [comment]
Yes certainly. I updated on latest SDKs versions (with binaries : .jar/.framework) : iOS SDK v0.10.0 && Android SDK v1.6.1. Will upgrade to next one ;)

**Comment by alamboley** [comment]
@aaustin is there any link for having native SDKs API in the same format than http://developer.android.com/reference/packages.html https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/index.html ?

**Comment by alamboley** [comment]
@aaustin hey Alex, I'm working on the createReferralCode method. I'm a bit struggling with date (I'm not used to managed them with Objective-C & Java):
From AS3, I'm sending a UTC String with this format [Tue Feb 1 00:00:00 2005 UTC](help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Date.html#toUTCString()).

In Java, I'm trying to do:
```java
Date d = null;
try {
	d = DateFormat.getInstance().parse(date);
} catch (ParseException e) {
	e.printStackTrace();
}
```

Objective-C:
```obj-c
NSDateFormatter* df = [[NSDateFormatter alloc] init];
[df setDateFormat:@""] // not sure of the format here.
NSDate* date = [df dateFromString:expiration];
```

Any ideas? Thanks.

**Comment by shortstuffsushi** [comment]
Try using a more universal format, it'll make it easier to parse on both sides and work for more platforms in the future (if necessary). Look up ISO-8601. Both iOS and Android have strategies for consuming these, though I don't know that they're built into either language/platform.

**Comment by shortstuffsushi** [comment]
Additionally, I'm pretty sure we send dates to the server in ISO-8601 to begin with, so you may not even need to turn them into date objects on the native side.

**Comment by shortstuffsushi** [comment]
Specifically, [iOS parsing](http://stackoverflow.com/questions/4999396/how-to-parse-a-date-string-into-an-nsdate-object-in-ios) and [Android parsing](http://stackoverflow.com/questions/2201925/converting-iso-8601-compliant-string-to-java-util-date) (ignore the Joda answer, that's unnecessary).

**Comment by alamboley** [comment]
Unfortunately the ISO-8601 format is not supported natively in AS3 :/

So I used the [time variable](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Date.html#time): *The number of milliseconds since midnight January 1, 1970, universal time.*
```obj-c
[NSDate dateWithTimeIntervalSince1970:time]
```
```java
new Date(date)
```

**Comment by jfreeney** [comment]
http://www.brooksandrus.com/blog/2009/02/23/convert-an-iso-8601-date-string-to-from-a-native-as3-date-object/

**Comment by shortstuffsushi** [comment]
That's fine, just something more universal. Either way you decide to go with that works for me.
