### ISSUE TITLE
InvokeEvent.INVOKE arguments is empty on iOS

### ISSUE THREAD

**Issue by alamboley** [BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK#3]
[applicationOpenURLSourceApplication](https://github.com/BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK/blob/40c56bdd22322d8fec376aa297cb525ab192bd5f/ios/BranchIosExtension/BranchIosExtension/BranchIosExtension.m#L199) is probably causing the issue. However I never saw an other way to implement it.

**Comment by jfreeney** [comment]
Seems to work on Android but broken on iOS

**Comment by shortstuffsushi** [comment]
Just FYI, your link seems to be broken -- currently pointing at getCredits. When you do line linking on github, you should make sure you use lines from a specific commit. You can do this from the "current" version by pressing "y."

**Comment by alamboley** [comment]
Wow, thanks for the tip @shortstuffsushi didn't know that! I've edited my link ;)

**Comment by alamboley** [comment]
>This is no longer empty - I think it is fixed by universal links and air having updated to support them
>jfreeney
