### ISSUE TITLE
Adding Credits support

### ISSUE THREAD

**Issue by alamboley** [BranchMetrics/AIR-ANE-Deferred-Deep-Linking-SDK#5]
https://dev.branch.io/references/http_api/#adding-credits

**Comment by alamboley** [comment]
@aaustin @shortstuffsushi Hey, is it the same thing than [Create Referral Code on Android](https://dev.branch.io/references/android_sdk/#create-referral-code) and [Create Promo Code on iOS](https://dev.branch.io/references/ios_sdk/#create-promo-code)?

Is there any way to give credits abstractly? (requested by @jfreeney).

**Comment by shortstuffsushi** [comment]
We renamed referral codes to promo codes to better indicate their intent. The same switch hasn't been made yet on Android.

Not sure what you mean by "give credits abstractly." I think you're saying just arbitrarily awarding credits, which is possible (via other APIs, I think), but not recommended. I don't have the docs offhand, but @derrickstaten should know about this.

**Comment by derrickstaten** [comment]
You can arbitrarily award credits. You should do this from your backend only. See https://dev.branch.io/references/http_api/#adding-credits
